---
# This playbook sets up a dev environment.

- name: set up dev env
  hosts: all
  roles:
    - {role: fzf, tags: ['fzf']}
    - {role: git, tags: ['git']}
    - {role: spotifyd, tags: ['spotifyd']}
