---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "artis3n/docker-arch-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    priviled: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
